var closeADA;$(document).ready(function(){var toolsHeight=$('#ada-tools').height();var toolsIconHeight=$('.ADA-icon').height();var toolsWidth=$('#ada-tools').width();var toolsIconWidth=$('.ADA-icon').width();var ada_position=$('#ada_position').val();var ada_layout=$('#ada_layout').val();$("#ads-tools-inner.drag").css('display','none').css('visibility','visible');prevHeight=$(window).height();prevWidth=$(window).width();if($('#ada-tools').hasClass('horizontal_topleft')||$('#ada-tools').hasClass('virtical_topleft')){$(window).resize(function(){var divClass='horizontal_topleft';setTimeout(function(){var currentHeight=$(window).height();var currentWidth=$(window).width();if(currentWidth<prevWidth){xPos=parseInt(readCookie('xPos'))-(prevWidth-currentWidth);}
if(currentWidth>prevWidth){xPos=parseInt(readCookie('xPos'))+(currentWidth-prevWidth);}
if(currentHeight<prevHeight){yPos=parseInt(readCookie('yPos'))-(prevHeight-currentHeight);}
if(currentHeight>prevHeight){yPos=parseInt(readCookie('yPos'))+(currentHeight-prevHeight);}
if(typeof xPos==='undefined'||xPos<0){xPos=0};if(typeof yPos==='undefined'||yPos<0){yPos=0};createCookie('xPos',xPos,1);createCookie('yPos',yPos,1);if($('#ada-tools').hasClass('virtical_topleft')){divClass='virtical_topleft';}
$('#ada-tools.'+divClass).animate({left:parseInt(readCookie('xPos')),top:parseInt(readCookie('yPos')),},{duration:100,});prevHeight=currentHeight;prevWidth=currentWidth;},500);});}
$('#ada-tools.virtical_topleft').draggable({containment:'window',scroll:false,start:function(event,ui){$(this).addClass('noclick');},stop:function(event,ui){var extraW=0;var extraH=0;var offset=$(this).offset();if(!$('#ads-tools-inner').is(':hidden')){extraH=extraH+(toolsHeight-toolsIconHeight-22);}
var xPos=offset.left-$(window).scrollLeft();var yPos=offset.top+extraH-$(window).scrollTop();createCookie('xPos',xPos,1);createCookie('yPos',yPos,1);}});$('#ada-tools.horizontal_topleft').draggable({containment:'window',scroll:false,start:function(event,ui){$(this).addClass('noclick');},stop:function(event,ui){var extraW=0;var extraH=0;var offset=$(this).offset();if(!$('#ads-tools-inner').is(':hidden')){extraW=extraW+(toolsWidth-toolsIconWidth-30);}
var xPos=(offset.left+extraW)-$(window).scrollLeft();var yPos=offset.top-$(window).scrollTop();createCookie('xPos',xPos,1);createCookie('yPos',yPos,1);}});var r=setTimeout((function(){$("#ada-tools.horizontal").stop().animate({right:-((toolsWidth-toolsIconWidth)-20)+'px'},{duration:500,});}),300);var rl=setTimeout((function(){setPosPreference('h','ada-tools.horizontal_topleft');}),300);function createCookie(name,value,days)
{if(days)
{var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString();}
else var expires="";document.cookie=name+"="+value+expires+"; path=/";}
function readCookie(name)
{var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++)
{var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)return c.substring(nameEQ.length,c.length);}
return null;}
function eraseCookie(name)
{createCookie(name,"",-1);}
function setColorPreference(colorPreference)
{if(colorPreference>=1&&colorPreference<=4)
{var colors=[{b:"#000000",t:"#ffffff"},{b:"#ffffff",t:"#000000"},{b:"#000000",t:"#ffff00"},{b:"#B30000",t:"#ffffff"}];}
var css="<style type='text/css'> * { background-color:"+colors[colorPreference-1].b+" !important; color:"+colors[colorPreference-1].t+" !important;} *:focus {color:"+colors[colorPreference-1].t+"; border:1px dotted "+colors[colorPreference-1].t+"}</style>";ADAStyle=$('#ADAStyle').html()+css;$('#ADAStyle').html(ADAStyle);createCookie('colorchange',colorPreference,1);}
function setLinksPreference(linkPreference){if(linkPreference==1){var css="<style type='text/css'> a{text-decoration:underline !important};</style>";ADAStyle=$('#ADAStyle').html()+css;$('#ADAStyle').html(ADAStyle);createCookie('linkchange',linkPreference,1);}}
function setPosPreference(p,elm){var dragxPos=0;var dragyPos=0;xPosPreference=readCookie('xPos');if(xPosPreference!==null){dragxPos=1;}
yPosPreference=readCookie('yPos');if(yPosPreference!==null){dragyPos=1;}
if(dragxPos==1&&dragyPos==1){$('#'+elm).stop().animate({left:xPosPreference+'px',top:yPosPreference+'px',},{duration:500,});}else{defaultPos(elm);}}
function WinPos(p,pos){var winWidth=$(window).width();var winHeight=$(window).height();if(p=='h'){pos=pos-(toolsWidth-toolsIconWidth-28);}else{pos=pos-(toolsHeight-toolsIconHeight-22);}
if(pos<0){pos=0;}
return pos;}
function defaultPos(elm){if(elm=='ada-tools.horizontal_topleft'){$('#'+elm).stop().animate({left:'0px'},{duration:500,});}else{$('#'+elm).animate({top:'0px'},{duration:500,});}}
function setFontPreference(fontPreference){if(fontPreference!=0){var fontSize=parseInt($('#fontSize').val());$('body *').each(function(){currentElementSize=parseFloat($(this).css('font-size'));currentElementLineheight=parseFloat($(this).css('line-height'));if(fontPreference==1){rate=currentElementSize+2;lineRate=currentElementLineheight+2;}else{rate=currentElementSize-2;lineRate=currentElementLineheight-2;}
$(this).animate({"font-size":rate+'px'});$(this).animate({"line-height":lineRate+'px'});});if(fontPreference==1){$('#fontSize').val(fontSize+1);}else{$('#fontSize').val(fontSize-1);}
var newfontSize=$('#fontSize').val();createCookie('fontchange',newfontSize,1);}}
var colorPreference=readCookie('colorchange');if(colorPreference&&colorPreference!=0)
{colorPreference=parseInt(colorPreference,10);setColorPreference(colorPreference);}
var linkPreference=readCookie('linkchange');if(linkPreference&&linkPreference==1)
{linkPreference=parseInt(linkPreference,10);setLinksPreference(linkPreference);}
var fontPreference=readCookie('fontchange');if(fontPreference&&fontPreference!=0)
{fontPreference=parseInt(fontPreference,10);$('body *').each(function(){currentElementSize=parseFloat($(this).css('font-size'));currentElementLineheight=parseFloat($(this).css('line-height'));rate=currentElementSize+(fontPreference*2);lineRate=currentElementLineheight+(fontPreference*2);$(this).animate({"font-size":rate+'px'});$(this).animate({"line-height":lineRate+'px'});$('#fontSize').val(fontPreference);});}
$('.ADA-colors').click(function()
{var colorPreference=parseInt($(this).data('color-preference'),10);setColorPreference(colorPreference);});$('.ADA-links').click(function()
{var linkPreference=parseInt($(this).data('link-preference'),10);setLinksPreference(linkPreference);});$('.ADA-fonts').click(function()
{var fontPreference=parseInt($(this).data('font-preference'),10);setFontPreference(fontPreference);});$('.ADA-revert').click(function()
{eraseCookie('colorchange');eraseCookie('linkchange');eraseCookie('fontchange');$('#ADAStyle').empty();$('body *').each(function(){$(this).css("font-size","");$(this).css("line-height","");$('#fontSize').val(0);});});$('.horizontal .ADA-icon').click(function()
{var rightPosition=$('#ada-tools.horizontal').css('right');var changePosition='0px';if(rightPosition=='0px'){changePosition=-((toolsWidth-toolsIconWidth)-20)+'px';$('.fa-arrow-right').hide();$('.fa-arrow-left').show();$('.ADA-tab').attr("tabindex",-1);$('.horizontal .ADA-icon').attr("aria-expanded",'false');var t1=setTimeout(function(){$("#ads-tools-inner").css('visibility','hidden');},500);}else{$('.fa-arrow-left').hide();$('.fa-arrow-right').show();$('.ADA-tab').attr("tabindex",0);$('.horizontal .ADA-icon').attr("aria-expanded",'true');$("#ads-tools-inner").css('visibility','visible');$('.color-1').focus();}
$("#ada-tools.horizontal").animate({right:changePosition},{duration:500,});});$('.virtical .ADA-icon').click(function()
{if(ada_position=='t'){var top=-((toolsHeight-toolsIconHeight)-12)+'px';var vPosition=$('#ada-tools.virtical').css('top');var changePosition='0px';if(vPosition=='0px'){changePosition=top;$('.fa-arrow-up').hide();$('.fa-arrow-down').show();$('.ADA-tab').attr("tabindex",-1);$('.virtical .ADA-icon').attr("aria-expanded",'false');var t2=setTimeout(function(){$("#ads-tools-inner").css('visibility','hidden');},500);}else{$('.fa-arrow-down').hide();$('.fa-arrow-up').show();$('.ADA-tab').attr("tabindex",0);$('.virtical .ADA-icon').attr("aria-expanded",'true');$("#ads-tools-inner").css('visibility','visible');$('.color-1').focus();}
$("#ada-tools.virtical").animate({top:changePosition},{duration:500,});}else{var bottom=-((toolsHeight-toolsIconHeight)-15)+'px';var vPosition=$('#ada-tools.virtical').css('bottom');var changePosition='10px';if(vPosition=='10px'){changePosition=bottom;$('.fa-arrow-up').show();$('.fa-arrow-down').hide();$('.ADA-tab').attr("tabindex",-1);$('.virtical .ADA-icon').attr("aria-expanded",'false');var t3=setTimeout(function(){$("#ads-tools-inner").css('visibility','hidden');},500);}else{$('.fa-arrow-down').show();$('.fa-arrow-up').hide();$('.ADA-tab').attr("tabindex",0);$('.virtical .ADA-icon').attr("aria-expanded",'true');$("#ads-tools-inner").css('visibility','visible');$('.color-1').focus();}
$("#ada-tools.virtical").animate({bottom:changePosition},{duration:500,});}});$('.horizontal_topleft .ADA-icon').click(function()
{if($('#ada-tools').hasClass('noclick')){$('#ada-tools').removeClass('noclick');}else{var Position=$('#ada-tools.horizontal_topleft').offset().left-$(window).scrollLeft();leftPosition=Position;if(!$('#ads-tools-inner').is(':hidden')){$("#ads-tools-inner").hide();$('.fa-plus-square-o').show();$('.fa-minus-square-o').hide();$('.ADA-tab').attr("tabindex",-1);$('.horizontal_topleft .ADA-icon').attr("aria-expanded",'false');$("#ada-tools.horizontal_topleft").css('left',readCookie('xPos')+'px');}else{$("#ada-tools.horizontal_topleft").css('left',WinPos('h',leftPosition)+'px');$('.fa-minus-square-o').show();$('.fa-plus-square-o').hide();$('.ADA-tab').attr("tabindex",0);$('.horizontal_topleft .ADA-icon').attr("aria-expanded",'true');$("#ads-tools-inner").show();$('.color-1').focus();}}});$('.virtical_topleft .ADA-icon').click(function()
{if($('#ada-tools').hasClass('noclick')){$('#ada-tools').removeClass('noclick');}else{var Position=$('#ada-tools.virtical_topleft').offset().top-$(window).scrollTop();vPosition=Position;if(!$('#ads-tools-inner').is(':hidden')){$("#ads-tools-inner").hide();$('.fa-plus-square-o').show();$('.fa-minus-square-o').hide();$('.ADA-tab').attr("tabindex",-1);$('.virtical_topleft .ADA-icon').attr("aria-expanded",'false');$("#ada-tools.virtical_topleft").css('top',readCookie('yPos')+'px');}else{$("#ada-tools.virtical_topleft").css('top',WinPos('v',vPosition)+'px');$('.fa-minus-square-o').show();$('.fa-plus-square-o').hide();$('.ADA-tab').attr("tabindex",0);$('.virtical_topleft .ADA-icon').attr("aria-expanded",'true');$("#ads-tools-inner").show();$('.color-1').focus();}}});if(ada_position=='t'){var t=setTimeout((function(){$("#ada-tools.virtical").animate({top:-((toolsHeight-toolsIconHeight)-12)+'px'},{duration:500,});}),300);}else if(ada_position=='tl'){var t=setTimeout((function(){setPosPreference('v','ada-tools.virtical_topleft');}),300);}else{var t=setTimeout((function(){$("#ada-tools.virtical").animate({bottom:-((toolsHeight-toolsIconHeight)-15)+'px'},{duration:500,});}),300);}
$("#ada-tools").mouseleave(function(){clearTimeout(closeADA);if(ada_layout=='h'){var currentPosition=$('#ada-tools.horizontal').css('right');}else{if(ada_position=='t'){var currentPosition=$('#ada-tools.virtical').css('top');}else{var currentPosition=$('#ada-tools.virtical').css('bottom');}}
if(currentPosition>='0px'){closeADA=setTimeout(function(){$('.ADA-icon').click();},5000);}});$("#ada-tools").mouseenter(function(){clearTimeout(closeADA);});});